# Generated by Django 3.2.9 on 2021-12-16 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0002_topbooks_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitems',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookitems',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topbooks',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
