# Generated by Django 3.2.9 on 2021-12-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0004_auto_20211216_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbooks',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='noveldust.Genrelist'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
