# Generated by Django 3.2.9 on 2022-01-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0008_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbooks',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noveldust.author'),
        ),
    ]
