# Generated by Django 3.2.9 on 2022-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0009_topbooks_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitems',
            name='samename',
        ),
        migrations.AddField(
            model_name='bookitems',
            name='bookfile',
            field=models.FileField(null=True, upload_to='media/bookfiles/<bound method Field.__str__ of <django.db.models.fields.related.ForeignKey>>'),
        ),
        migrations.AlterField(
            model_name='bookitems',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/bookcover/%Y-%m-%d'),
        ),
    ]
