# Generated by Django 3.2.9 on 2022-01-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0011_alter_bookitems_bookfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitems',
            name='bookfile',
            field=models.FileField(null=True, upload_to='media/bookfiles/<bound method Field.__str__ of <django.db.models.fields.CharField>>'),
        ),
    ]
