# Generated by Django 3.2.9 on 2022-01-26 13:35

from django.db import migrations, models
import noveldust.models


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0019_alter_bookitems_bookfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitems',
            name='bookfile',
            field=models.FileField(null=True, upload_to=noveldust.models.BookItems.file_name_path),
        ),
    ]
