# Generated by Django 3.2.9 on 2022-01-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0020_alter_bookitems_bookfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitems',
            name='bookfileurl',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookitems',
            name='samecover',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
