# Generated by Django 3.2.9 on 2022-01-31 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noveldust', '0021_auto_20220127_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitems',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='bookitems',
            name='samecover',
        ),
        migrations.AlterField(
            model_name='bookitems',
            name='bookfile',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookitems',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topbooks',
            name='topcover',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='BookRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noveldust.topbooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noveldust.topbooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
