# Generated by Django 3.2.9 on 2022-01-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0022_auto_20220131_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitems',
            name='bookfile',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookitems',
            name='bookfileurl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='topbooks',
            name='topcover',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
