# Generated by Django 3.2.9 on 2022-01-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0023_auto_20220131_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitems',
            name='bookfileurl',
        ),
    ]
