# Generated by Django 3.2.9 on 2022-02-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveldust', '0025_alter_topbooks_topcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbooks',
            name='topcover',
            field=models.ImageField(blank=True, null=True, upload_to='media/topcovers/%Y-%m'),
        ),
    ]
