# Generated by Django 3.2.9 on 2021-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustmain', '0003_auto_20211216_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbooks',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topbooks',
            name='topcover',
            field=models.ImageField(upload_to='media/topcover/%Y-%m-%d'),
        ),
    ]
